"""add websocket_logs table

Revision ID: 297c20036381
Revises:
Create Date: 2025-11-23 08:50:14.790962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "297c20036381"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "websocket_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tender_id", sa.String(), nullable=False),
        sa.Column(
            "message_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_websocket_logs_created_at"),
        "websocket_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_websocket_logs_tender_id", "websocket_logs", ["tender_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_websocket_logs_tender_id", table_name="websocket_logs")
    op.drop_index(op.f("ix_websocket_logs_created_at"), table_name="websocket_logs")
    op.drop_table("websocket_logs")
    # ### end Alembic commands ###
