"""add wishlist table

Revision ID: add_wishlist_table
Revises: 297c20036381
Create Date: 2025-11-24

To run this migration manually:
  cd backend
  uv run alembic upgrade head

The migration will also run automatically when starting the backend via docker-compose.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "add_wishlist_table"
down_revision: Union[str, Sequence[str], None] = "297c20036381"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishlist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wishlist_created_at"),
        "wishlist",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wishlist_email"),
        "wishlist",
        ["email"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wishlist_email"), table_name="wishlist")
    op.drop_index(op.f("ix_wishlist_created_at"), table_name="wishlist")
    op.drop_table("wishlist")
    # ### end Alembic commands ###
